version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: heroes_api_backend
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    tty: true
    # command: docker exec -it heroes_api_backend /bin/bash
